name: Update Last Updated Timestamp

on:
  push:
    branches:
      - main  # or 'master' or your default branch

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get last commit date
        run: |
          git log -1 --format="%cd" --date=short > last-updated.txt

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add last-updated.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update last-updated.txt"
          git push
